# Generated by Django 3.1.3 on 2020-12-01 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FestivalBrand', models.CharField(max_length=30, verbose_name='Jméno')),
                ('Place', models.CharField(max_length=400, verbose_name='Místo')),
                ('Genre', models.CharField(max_length=30, verbose_name='Žánr')),
                ('Start', models.DateField(default='2020-01-01', verbose_name='Začátek')),
                ('End', models.DateField(default='2020-02-01', verbose_name='Konec')),
                ('PriceForTicket', models.IntegerField(verbose_name='Cena za lístek')),
                ('Capacity', models.IntegerField(verbose_name='Kapacita')),
                ('photoLogo', models.ImageField(blank=True, null=True, upload_to='./FestivalReservations/static/images/festival', verbose_name='Fotografie')),
            ],
        ),
        migrations.CreateModel(
            name='Interpret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Members', models.CharField(max_length=100)),
                ('photoLogo', models.ImageField(blank=True, null=True, upload_to='./FestivalReservations/static/images/interpret')),
                ('Rating', models.IntegerField()),
                ('Genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.IntegerField()),
                ('Festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FestivalReservations.festival')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Start', models.TimeField()),
                ('End', models.TimeField()),
                ('Interpret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FestivalReservations.interpret')),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FestivalReservations.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tickets', models.IntegerField()),
                ('Paid', models.BooleanField(default=False, null=True)),
                ('Festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FestivalReservations.festival')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
        ),
    ]
