# Generated by Django 3.1.3 on 2020-12-01 20:00

from django.db import migrations
from django.contrib.auth.models import User, Group


def InitializeData(apps, schema_editor):

    customer = Group(name="customer")
    customer.save()

    cashier = Group(name="cashier")
    cashier.save()

    organizer = Group(name="organizer")
    organizer.save()

    admin = Group(name="admin")
    admin.save()

    user1 = User(username="customer", email="test@email.cz")
    user2 = User(username="cashier", email="neco@email.cz")
    user3 = User(username="organizer", email="something@email.cz")
    user4 = User(username="admin", email="some@email.cz")

    user1.set_password("iisfit2020")
    user2.set_password("iisfit2020")
    user3.set_password("iisfit2020")
    user4.set_password("iisfit2020")

    user1.save()
    user2.save()
    user3.save()
    user4.save()

    user1.groups.add(customer)
    user2.groups.add(cashier)
    user3.groups.add(organizer)
    user4.groups.add(admin)


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalReservations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(InitializeData)
    ]
